### ISSUE TITLE
Feature Request: detect invalid modid or item/fluid etc. name in brackets

### ISSUE THREAD

**Issue by Keridos** [Yesterday17/ZenScript#13]
As the title states: detect invalid entries in Bracket definitions, for example typos like <minecraft:oak_woood> or <mincraft:obisidian>.

If this is working already then sorry, but at least my vscode happily autocompletes but does not provide feedback on wrong definitions.

**Comment by Yesterday17** [comment]
I intend to make this work with `#ignoreBracketError`, and it would come with #11 since they need something common.
