### ISSUE TITLE
Add new preprocessors.

### ISSUE THREAD

**Issue by friendlyhj** [Yesterday17/ZenScript#15]
Putting the `#ikwid` preprocessor on a script file will make it that Logger warnings aren't printed to the player chat

`#sideonly client` and `#sideonly server`

`#disable_search_tree`  will disable recipe tree recalculation which may speed up game loading.

Putting the `#profile` preprocessor on a script file will profile the script actions

**Comment by Yesterday17** [comment]
Seems it's preprocessor not listed in wiki. I'll add them soon.

**Comment by Yesterday17** [comment]
Added all preprocessors at https://github.com/CraftTweaker/CraftTweaker/tree/1.12/CraftTweaker2-API/src/main/java/crafttweaker/preprocessor and updated `v0.1.39`.

![Screenshot_20200222_131615](https://user-images.githubusercontent.com/8667822/75086986-8dfe2880-5575-11ea-909c-122b44c7d00b.png)

**Comment by friendlyhj** [comment]
Great. But I don't know why, the IgnoreBracketErrorPreprocessor is called by `#ignoreBracketErrors`, like the wiki said. You missed an "s".

**Comment by Yesterday17** [comment]
@friendlyhj I deleted the `s` because it doesn't have `s` in code. I think it's about the wiki which had a mistake.
https://github.com/CraftTweaker/CraftTweaker/blob/d58bf4b022be74eb9c2799e76c81360ea7fdb6f9/CraftTweaker2-API/src/main/java/crafttweaker/preprocessor/IgnoreBracketErrorPreprocessor.java#L14

**Comment by friendlyhj** [comment]
Yes, I know that. But my test tells me, the `s` is needed.
So the code has a mistake, the wiki is right. That's pretty strange.

**Comment by friendlyhj** [comment]
Anyway, the new preprocessors don't have blue highlight.

**Comment by Yesterday17** [comment]
hmm, seems there're some other problems.

**Comment by Yesterday17** [comment]
Updated v0.1.40, fixed highlight and some minor bugs.

**Comment by friendlyhj** [comment]
But the preprocessor list still don't have the `s`.
I think you'd better add the `s`. Extra letters don't matter, but the missing ones will cause problem.

**Comment by Yesterday17** [comment]
hmm, seems i misunderstood what it means
Should be fixed now.
