### ISSUE TITLE
[BUG]import脚本文件报错

### ISSUE THREAD

**Issue by friendlyhj** [Yesterday17/ZenScript#17]
![image](https://user-images.githubusercontent.com/30400991/78517180-e409f100-77ee-11ea-8cf6-37bbe5afb08e.png)

**Comment by Yesterday17** [comment]
绝了 我忘记可以本地 import 了

**Comment by Yesterday17** [comment]
Fixed in `v0.1.43`.

**Comment by friendlyhj** [comment]
赞！不过跨脚本的静态变量/函数能用了，不过ZenClass还不能。

**Comment by Yesterday17** [comment]
@friendlyhj 对 zenClass 还没写 之后补上（
