### ISSUE TITLE
[BUG]无法解析文件

### ISSUE THREAD

**Issue by Death-123** [Yesterday17/ZenScript#21]
当工作区同时存在config文件夹时,插件会报错,功能失效
![image](https://user-images.githubusercontent.com/50763371/78764143-b4a6e000-79b8-11ea-9f6e-501b9c5a5a91.png)

**Comment by Yesterday17** [comment]
无法复现，有详细内容描述吗

![image](https://user-images.githubusercontent.com/8667822/78764890-c6d54e00-79b9-11ea-91be-2dc62f4a12f2.png)

**Comment by Death-123** [comment]
![image](https://user-images.githubusercontent.com/50763371/78765153-2cc1d580-79ba-11ea-9bd8-90060a99f4ec.png)
工作区这样子设置的

**Comment by Yesterday17** [comment]
好 复现了
