### ISSUE TITLE
Errors when plugin tries to load the scripts folder

### ISSUE THREAD

**Issue by superspeeder** [Yesterday17/ZenScript#22]
the request "zenScript/fsReadDirectory" fails, and the error message is: 
```
(node:12192) UnhandledPromiseRejectionWarning: Error: Request zenScript/fsReadDirectory failed with message: Unable to resolve filesystem provider with relative file path 'c:\Users\superspeeder\Modpack\scripts'
    at processMessageQueue (c:\Users\superspeeder\.vscode\extensions\yesterday17.zenscript-0.2.1\node_modules\vscode-jsonrpc\lib\main.js:276:17)
    at Immediate.<anonymous> (c:\Users\superspeeder\.vscode\extensions\yesterday17.zenscript-0.2.1\node_modules\vscode-jsonrpc\lib\main.js:260:13)
    at processImmediate (internal/timers.js:439:21)
```
the request sent to server when I set the trace server setting to verbose is
```
[Trace - 3:13:10 PM] Received request 'zenScript/fsReadDirectory - (1)'.
Params: {
    "$mid": 1,
    "path": "\\Users\\superspeeder\\Modpack\\scripts",
    "scheme": "c"
}
```
Right between the request reception and the error is this message from the trace
```
[Trace - 3:13:10 PM] Sending response 'zenScript/fsReadDirectory - (1)'. Processing request took 21ms
```
Also the .zsrc file is 17.2 MB, I have version 0.2.1 of your ZenScript plugin installed, and I used version 0.1.23 of Probe in the pack to generate the .zsrc

The about section of vs code:
Version: 1.44.0 (system setup)
Commit: 2aae1f26c72891c399f860409176fe435a154b13
Date: 2020-04-07T23:31:18.860Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

Any help would be appreciated.

**Comment by Yesterday17** [comment]
Try this version? (To upload to GitHub, I added `.zip` . So you need to remove the `.zip` postfix before install)

[zenscript-0.2.1.vsix.zip](https://github.com/Yesterday17/ZenScript/files/4464104/zenscript-0.2.1.vsix.zip)

**Comment by superspeeder** [comment]
that version generated the same set of errors again.

**Comment by Yesterday17** [comment]
hmm, closed accidentally

**Comment by friendlyhj** [comment]
This bug is fatal. I can't use bracket handlers / import auto complete. I have gone back the plugin to `0.1.43`.

**Comment by Yesterday17** [comment]
Seems I've found the cause, but that's strange. I can't understand why `v0.1.43` works. :thinking:

**Comment by Yesterday17** [comment]
Sorry for late reply, but could you please try the latest published `v0.2.2`? It might fix this issue.

**Comment by superspeeder** [comment]
the latest update seems to have fixed all of the issues with auto completion

**Comment by superspeeder** [comment]
I now get an error from when using the <fluid:lava> tag that says that `BracketHandler <fluid:lava> does not exist.`
