### ISSUE TITLE
[BUG] 预处理器和 as 关键词没有高亮

### ISSUE THREAD

**Issue by friendlyhj** [Yesterday17/ZenScript#23]
![image](https://user-images.githubusercontent.com/30400991/79032743-7dfcdf80-7bdb-11ea-8106-fe3edae61f7b.png)
![image](https://user-images.githubusercontent.com/30400991/79032745-848b5700-7bdb-11ea-83a3-084646027cd9.png)

**Comment by Yesterday17** [comment]
测试了一下，`as` 高亮在默认主题 Dark 下没有高亮，但是在其他主题下都能正常高亮，属于主题问题，换主题就可以了，如下例：
![Screenshot_20200411_133511](https://user-images.githubusercontent.com/8667822/79036271-4866ef00-7bf9-11ea-8684-cbd8e036917b.png)

同时经过测试，TypeScript 的类型标注在默认主题下也无法正常显示高亮。
预处理器现在修改了一下，但仍然是一样的问题，如果主题不支持的话也没有高亮显示。
