### ISSUE TITLE
Keyword completion broken in ZenScript v0.2.1

### ISSUE THREAD

**Issue by baka4n** [Yesterday17/ZenScript#24]
The current solution is to go back to one version

**Comment by SeraphJACK** [comment]
大家都是中国人.jpg

**Comment by Yesterday17** [comment]
说实话，没看懂（

**Comment by friendlyhj** [comment]
![没有自动完成](https://user-images.githubusercontent.com/30400991/80277362-02457b80-8721-11ea-91f6-5d5fe165ed0c.png)
没有自动完成

![有自动完成](https://user-images.githubusercontent.com/30400991/80277386-1b4e2c80-8721-11ea-859e-4acf36a03400.png)
有自动完成

![关键字没有自动完成](https://user-images.githubusercontent.com/30400991/80277449-9f081900-8721-11ea-9ca9-426941fb4387.png)
关键字没有自动完成

**Comment by Yesterday17** [comment]
第一个补全暂时还没有实现，而且预计短期内也无法实现。
第二个自动完成是编辑器自带的，记忆你之前输入的内容后给出的补全，和本扩展没有关系。
最后一个是遗漏的关键字补全，下个版本加上（

**Comment by Yesterday17** [comment]
最后一个补全已在 v0.2.2 补上，包括 zenConstructor 和其他两个别名。

**Comment by Yesterday17** [comment]
如果你想要的是第一种的补全，可以跟踪 #11 的动态（然而最近 ddl 一大堆，慢慢摸吧

**Comment by friendlyhj** [comment]
> 第一个补全暂时还没有实现，而且预计短期内也无法实现。
> 第二个自动完成是编辑器自带的，记忆你之前输入的内容后给出的补全，和本扩展没有关系。
> 最后一个是遗漏的关键字补全，下个版本加上（

`instanceof` 也补一个不（

**Comment by Yesterday17** [comment]
> > 第一个补全暂时还没有实现，而且预计短期内也无法实现。
> 
> > 第二个自动完成是编辑器自带的，记忆你之前输入的内容后给出的补全，和本扩展没有关系。
> 
> > 最后一个是遗漏的关键字补全，下个版本加上（
> 
> 
> 
> `instanceof` 也补一个不（

这个不大适合做成全局的。instanceof 的补全是有语境的，估计得等到解释器全写完在那一层弄补全了（
