### ISSUE TITLE
Add bracket handler for wildcards

### ISSUE THREAD

**Issue by rlnt** [Yesterday17/ZenScript#25]
Currently, you get an error when you use wildcards for item IDs:
BracketHandler <actuallyadditions:block_crystal:*> does not exist.

In zenscript it's possible to cover all subtypes of an item by using the wildcard '*'. That should not throw an error.

ZenScript extension: v0.2.2
Probe mod: v0.1.23

**Comment by Yesterday17** [comment]
`v0.2.3` fixed this issue.
