### ISSUE TITLE
Liquid does not exist although shown in intellisense

### ISSUE THREAD

**Issue by rlnt** [Yesterday17/ZenScript#26]
I am currently having a problem that liquids in my scripts are throwing errors like:
```
BracketHandler <liquid:refinedcanolaoil> does not exist.
```
The interesting part is that it's shown in the intellisense and it's also included in my .zsrc file from the probe mod.
It happens with any liquid in many different files so it's probably a problem by the extension.
It's also weird that the message is shown twice which you can see here:
![](https://i.imgur.com/l9OZr8v.png)

**Versions**
ZenScript: v0.2.3
Probe: v0.1.23
VSCode: 1.44.2

**Comment by Yesterday17** [comment]
Does this issue remain if replace ‘liquid’ with ‘fluid’?

**Comment by rlnt** [comment]
Yes, it does.
If you want to take a look, here are the files which includes the two scripts with the errors and my .zsrc file.
[scripts.zip](https://github.com/Yesterday17/ZenScript/files/4555144/scripts.zip)

**Comment by Yesterday17** [comment]
hmm, seems the way it judges whether liquid exists is totally wrong

**Comment by Yesterday17** [comment]
DONE  Published yesterday17.zenscript@0.2.4
Your extension will live at https://marketplace.visualstudio.com/items?itemName=yesterday17.zenscript (might take a few minutes for it to show up).

**Comment by rlnt** [comment]
Yep, that fixed it. Thanks a lot! :)
