### ISSUE TITLE
关于 Bracket Handler 检查的建议

### ISSUE THREAD

**Issue by friendlyhj** [Yesterday17/ZenScript#29]
![image](https://user-images.githubusercontent.com/30400991/81471627-06938d80-9225-11ea-9c79-8491266cf327.png)

这个是 CompatSkills 的 Skill Bracket Handler，我也不强求对此的支持，只希望这些 probe 暂不支持的Bracket Handler 可以不检查是否存在。

一个建议就是能读取所有的 Bracket Handler Type，其中存在的但 probe 不能导出其名下的内容，也不进行对其的检查。

Refer to #27

**Comment by Yesterday17** [comment]
最近没什么时间修，下次更新估计至少得一周以后了……
可以用 `#ignoreBracketError`先顶一顶，就当这个功能暂时不存在（

**Comment by Yesterday17** [comment]
下一个版本会推送忽略未知 `BracketHandler` 的功能，但这需要你手动关闭 `modIdItemCompletion` 这一选项。这意味着你必须在所有**物品**的 `BracketHandler` 前增加 `item:` 这一前缀。

这样做的原因是当该选项打开时，我们无法判断究竟 `<xxx:yyy>` 中的 `xxx` 究竟是错误的 `modid` 还是未知的 `BracketHandler`。

并且，`ZenScript 1.14+`（或者说 `ZenCode`）已经强制使用 `<item:` 来指定物品了。因此之后关于这部分的策略也不会作太大修改，仅作 Bug 修复。
