### ISSUE TITLE
发现一个文本解析器的bug

### ISSUE THREAD

**Issue by byronwanbl** [Yesterday17/ZenScript#34]
我发现文本解析后生成的ast树的内容似乎没有任何意义。

[ast.zip](https://github.com/Yesterday17/ZenScript/files/5049959/ast.zip)

**Comment by Yesterday17** [comment]
确实，因为还没写完（

**Comment by byronwanbl** [comment]
那还是希望作者大大继续吧这个插件写完，给整合包作者带来更好的魔改体验。
