### ISSUE TITLE
Operator "Less Than"(<) makes all codes after it blue

### ISSUE THREAD

**Issue by RisingInIris2017** [Yesterday17/ZenScript#43]
### VS Code version:
1.54.1
### ZenScript plugin version:
0.2.8
### Description of the problem:
Let's see this picture:
![1](https://user-images.githubusercontent.com/28519848/116364159-7c2daa80-a836-11eb-8abe-5b25943236a4.png)
the bool operator Less Than makes all codes after it become blue and lost their respective syntax highlight color.

**Comment by Yesterday17** [comment]
![image](https://user-images.githubusercontent.com/8667822/116378415-b0a86300-a844-11eb-852a-859bc46bcc22.png)

Fixed

**Comment by Yesterday17** [comment]
```
DONE  Published yesterday17.zenscript@0.2.9
Your extension will live at https://marketplace.visualstudio.com/items?itemName=yesterday17.zenscript (might take a few minutes for it to show up).
```
