### ISSUE TITLE
VSCode plugin falsely detects trailing comma as error

### ISSUE THREAD

**Issue by MaxNeedsSnacks** [Yesterday17/ZenScript#6]
This is a *very* minor issue with the vscode plugin, but it currently detects a trailing comma at the end of a list, for example like this:
![Example](https://user-images.githubusercontent.com/12750501/54877909-2ef3d900-4e25-11e9-952c-9c668a56443d.png)
as an error in the script file, even though the ZenScript interpreter can deal just fine with trailing commas ^^

**Comment by Yesterday17** [comment]
Fixed & Published.

> Successfully published yesterday17.zenscript@0.1.31!
> Your extension will live at https://marketplace.visualstudio.com/items?itemName=yesterday17.zenscript (might take a few seconds for it to show up).
