### ISSUE TITLE
zenscript falsely detects  slash as error

### ISSUE THREAD

**Issue by luoxingzlx** [Yesterday17/ZenScript#7]
![snipaste_20190425_144708](https://user-images.githubusercontent.com/44374013/56715570-a3929e00-676a-11e9-8bb9-137c671d1476.png)

**Comment by Yesterday17** [comment]
卧槽 还能这么用的吗 我去修

**Comment by luoxingzlx** [comment]
@Yesterday17 tinkersforgeing作者命名奇葩而已，按TIC的方式，材料应该用nbt写才对

**Comment by Yesterday17** [comment]
![image](https://user-images.githubusercontent.com/8667822/56741853-3b61ad80-67a6-11e9-9ced-9b2b1ee5d623.png)
修了 如果有什么别的特殊字符再说（

**Comment by Yesterday17** [comment]
Successfully published yesterday17.zenscript@0.1.33!
Your extension will live at https://marketplace.visualstudio.com/items?itemName=yesterday17.zenscript (might take a few seconds for it to show up).

**Comment by luoxingzlx** [comment]
谢了
