### ISSUE TITLE
Always getting errors

### ISSUE THREAD

**Issue by RakDuhl** [Yesterday17/ZenScript#8]
The extension keeps giving me this message, even tho the workspace has a folder named scripts.

Is there any way for fixing this?

> ZenScript didn't enable all its features! Please check your folder name, it must be 'scripts', or a folder in your workspace must be named 'scripts'.

**Comment by Yesterday17** [comment]
Could you show me the structure of your folder?
And which folder did you open? If you opened `minecraft` folder, you need to enable `supportMinecraftFolderMode` in settings.

**Comment by RakDuhl** [comment]
my workspace is opened in a big `Instance` folder with many modpacks, so i have it all together
and i don't know what exactly mean with `settings`...
minecraft mod configs or VS Code?

**Comment by Yesterday17** [comment]
hmmm... A bit `Instance` folder... Maybe `MultiMC`?

I recommend to open the exact modpack folder which you'd like to edit. If you've **enabled** `supportMinecraftFolderMode` in the setting of `VSCode`, you can just open the **minecraft** folder of the modpack you'd like to edit. If not, you can **only** open the **scripts** folder.

Note that no matter which way you use to open the folder, `Probe` is need to generate .zsrc under `scripts` folder.

**Comment by RakDuhl** [comment]
It is `MultiMC`, but it's the `Instance` folder where my workspace is saved in

![grafik](https://user-images.githubusercontent.com/18248606/57943992-de08da00-78d5-11e9-9649-2dbe2e3d70bf.png)

**Comment by Yesterday17** [comment]
@RakDuhl Just open the `.minecraft` folder and enable `supportMinecraftFolderMode`, then it should work.

**Comment by Yesterday17** [comment]
@RakDuhl Have you solved this problem? Feel free to reopen this issue if this problem still exists.

**Comment by RakDuhl** [comment]
sorryy for very late reply, yes! it finally solved!
